apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: infra-tools
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.27.0
    chart: loki
    helm:
      releaseName: loki
      valuesObject:
        deploymentMode: SingleBinary
        singleBinary:
          replicas: 1
        loki:
          auth_enabled: false
        monitoring:
          selfMonitoring:
            enabled: false
        test:
          enabled: false
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
