apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-postgres
  namespace: infra-tools
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: application
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 12.5.6
    helm:
      releaseName: mlflow-postgres
      valuesObject:
        image:
          tag: "16.3.0-debian-12-r4"
        auth:
          username: mlflow
          password: mlflowpass
          database: mlflow
        primary:
          service:
            type: ClusterIP
            ports:
              postgresql: 5432
          persistence:
            enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
