apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: infra-tools
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.16.6
    chart: promtail
    helm:
      releaseName: promtail
      valuesObject:
        config:
          clients:
            - url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push
          snippets:
            extraScrapeConfigs: |
              - job_name: final-ml-service
                kubernetes_sd_configs:
                  - role: pod
                relabel_configs:
                  - source_labels: [__meta_kubernetes_namespace]
                    action: keep
                    regex: application
                  - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
                    action: keep
                    regex: final-ml-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
